//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kex.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\vbnet")]
        public string STL_PATH {
            get {
                return ((string)(this["STL_PATH"]));
            }
            set {
                this["STL_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EX_")]
        public string GROUP_PREFIX {
            get {
                return ((string)(this["GROUP_PREFIX"]));
            }
            set {
                this["GROUP_PREFIX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string DEFAULT_FACETRES {
            get {
                return ((string)(this["DEFAULT_FACETRES"]));
            }
            set {
                this["DEFAULT_FACETRES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RESET_UCS {
            get {
                return ((bool)(this["RESET_UCS"]));
            }
            set {
                this["RESET_UCS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MOVE_XYZ {
            get {
                return ((bool)(this["MOVE_XYZ"]));
            }
            set {
                this["MOVE_XYZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EXPLODE {
            get {
                return ((bool)(this["EXPLODE"]));
            }
            set {
                this["EXPLODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LAYER_PER_BLOCK {
            get {
                return ((bool)(this["LAYER_PER_BLOCK"]));
            }
            set {
                this["LAYER_PER_BLOCK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExampleLayerName1,ExampleLayerName2")]
        public string EXCEPTION_LAYERS {
            get {
                return ((string)(this["EXCEPTION_LAYERS"]));
            }
            set {
                this["EXCEPTION_LAYERS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXCEPTION_ON {
            get {
                return ((bool)(this["EXCEPTION_ON"]));
            }
            set {
                this["EXCEPTION_ON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool USE_NEW_DRAWING {
            get {
                return ((bool)(this["USE_NEW_DRAWING"]));
            }
            set {
                this["USE_NEW_DRAWING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool USE_C4D_SCRIPT {
            get {
                return ((bool)(this["USE_C4D_SCRIPT"]));
            }
            set {
                this["USE_C4D_SCRIPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\vbnet\\kex.py")]
        public string PY_PATH {
            get {
                return ((string)(this["PY_PATH"]));
            }
            set {
                this["PY_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool USE_CUSTOM_PROPERTIES {
            get {
                return ((bool)(this["USE_CUSTOM_PROPERTIES"]));
            }
            set {
                this["USE_CUSTOM_PROPERTIES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Title")]
        public string PROPERTY_NAME {
            get {
                return ((string)(this["PROPERTY_NAME"]));
            }
            set {
                this["PROPERTY_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USE_TIMEOUT {
            get {
                return ((bool)(this["USE_TIMEOUT"]));
            }
            set {
                this["USE_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TIMEOUT_SELECTEDITEM {
            get {
                return ((int)(this["TIMEOUT_SELECTEDITEM"]));
            }
            set {
                this["TIMEOUT_SELECTEDITEM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NESTED_BLOCKS {
            get {
                return ((bool)(this["NESTED_BLOCKS"]));
            }
            set {
                this["NESTED_BLOCKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CLOSE_NEW_DWG {
            get {
                return ((bool)(this["CLOSE_NEW_DWG"]));
            }
            set {
                this["CLOSE_NEW_DWG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SOLID_OUTSIDE_BLOCKS {
            get {
                return ((bool)(this["SOLID_OUTSIDE_BLOCKS"]));
            }
            set {
                this["SOLID_OUTSIDE_BLOCKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool STLOUT {
            get {
                return ((bool)(this["STLOUT"]));
            }
            set {
                this["STLOUT"] = value;
            }
        }
    }
}
